---
title: "Proyecto de Kickstarter"
output:
  html_document:
    df_print: paged
---

1.  Se procede a obtener las librerías a utilizar

```{r}
library(dplyr)
library(ggplot2)
library(gridExtra)
library(tidyr)
library(reshape2)
library(RColorBrewer)
library(ggrepel)
```

2.  Se realiza la lectura del archivo de kickstarter

```{r}
y <- readLines('Datosks.csv')
y <- gsub("\"\"N,0\"\"\"\"\"\"", 'undefined', y)
y <- gsub(",\"(.*)\",", ',,', y)
y <- gsub("\"",'', y)
y <- gsub(";",'', y)
y<- textConnection(y)
df <- as_tibble(read.csv( y  , header=T, encoding = "UTF-8"),comment.char ="")
close(y)
glimpse(df)
y <- readLines('Datosks.csv')
```

3.  Se procede a analizar la correctitud en que obtuvo las variables buscando valores nulos

```{r}
# Valores que no aplica
sum(is.na(df))
df %>% summarise_all(~ sum(is.na(.)))
df %>% filter(is.na(df$usd.pledged))
# Comprobación del caracter 
df %>% filter( grepl(',',df$name) ) 
# Comprobacion de espacios
espacios <-  as.data.frame(which(df=="", arr.ind=TRUE))
df[espacios$row,]
espacios <-  as.data.frame(which(df==" ", arr.ind=TRUE))
df[espacios$row,]

# Falta insepccionar por esos 4 filas faltantes


```

```{r}
df <- as_tibble(df)

dfTime <- df%>%
  mutate(
    deadline = strptime(deadline, format = "%Y-%m-%d"),
    launched = strptime(launched, format = "%Y-%m-%d"),
    days = as.numeric(deadline - launched),
    season_days=cut(days,c( seq (0,120,by = 30),Inf ) , include.lowest = TRUE)
    )%>%
  select(days,name,season_days)%>% group_by(season_days)%>%summarise(count = length(season_days))
dfTime
```

```{r}

daysGroup <- 
  cut(dfTime$days,c( seq (0,120,by = 30),Inf ) , include.lowest = TRUE)
aggregate(days ~ daysGroup, dfTime, sum)



```

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).
